version: '3.6'
services:
  postgres-dev:
    image: postgres:13-alpine
    container_name: postgres-dev
    restart: unless-stopped

    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    volumes:
      - /etc/localtime:/etc/localtime:ro

    ports:
      - 5432:5432
